name: $(Date:yyyyMMdd)$(Rev:-rr)

variables:
  Label_Initialization: 'Initialization:'
  Label_DotNet: '.NET:'
  Label_NodeJS: 'node.js:'

  DotNet_BuildConfiguration: 'Release'
  DotNet_SessionSolution: 'CoreIpc.sln'
  DotNet_MainProjectName: 'UiPath.CoreIpc'
  DotNet_MainProjectPath: './src/UiPath.CoreIpc/UiPath.CoreIpc.csproj'
  DotNet_ArtifactName: 'NuGet package'
  
  NodeJS_DotNet_BuildConfiguration: 'Debug'
  NodeJS_ProjectPath: './src/Clients/nodejs'
  NodeJS_ArchivePath: './src/Clients/nodejs.zip'
  NodeJS_ArtifactName: 'NPM package'
  NodeJS_NetCoreAppTargetDir_RelativePath: 'dotnet/UiPath.CoreIpc.NodeInterop/bin/Debug/netcoreapp3.1'
  NodeJS_DotNetNodeInteropProject : './src/Clients/nodejs/dotnet/UiPath.CoreIpc.NodeInterop/UiPath.CoreIpc.NodeInterop.csproj'
  NodeJS_DotNetNodeInteropSolution: './src/Clients/nodejs/dotnet/UiPath.CoreIpc.NodeInterop.sln'

jobs:
  # The following 3 jobs will run in parallel:
            
  - job:
    displayName: '.NET on Windows'
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: azp-initialization.yaml
      - template: azp-dotnet.yaml
      - template: azp-dotnet-dist.yaml

  - job:
    displayName: 'node.js on Windows'
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: azp-initialization.yaml
      - template: azp-nodejs.yaml
      - template: azp-nodejs-dist.yaml

  - job:
    displayName: 'node.js on Ubuntu'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azp-initialization.yaml
      - template: azp-nodejs.yaml

