trigger:
- 'feature/init-azure-pipelines'

name: $(Date:yyyyMMdd)$(Rev:-rr)

pool:
  vmImage: 'windows-2019'

variables:
  BuildConfiguration: 'Release'
  SessionSolution: 'CoreIpc.sln'
  MainProjectName: 'UiPath.CoreIpc'

steps:
  # - task: VSBuild@1
  #   displayName: "Restore, build and pack"
  #   inputs:
  #     solution: '$(SessionSolution)'
  #     msbuildArgs: '/p:Version=$(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr) /restore'
  #     configuration: '$(BuildConfiguration)'
  #     maximumCpuCount: true

  - powershell: |
      $xml = [Xml] (Get-Content .\src\UiPath.CoreIpc\UiPath.CoreIpc.csproj)
      $version = [String] $xml.Project.PropertyGroup.Version
      $version = $version.Trim()
      
      Write-Host "##vso[task.setvariable variable=Version;]$version"
    displayName: 'Get version from csproj'

  - task: DotNetCoreCLI@2
    displayName: "Restore, build and pack"
    inputs:
      projects: '$(SessionSolution)'
      arguments: '--configuration $(BuildConfiguration) -p:Version="$(Version)-$(Build.BuildNumber)"'
      
  - task: DotNetCoreCLI@2
    displayName: "Run unit tests"
    inputs:
      command: 'test'
      projects: '**/*Tests*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: CopyFiles@2
    displayName: 'Copy nupkg to $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: 'src\UiPath.CoreIpc\bin\$(BuildConfiguration)\'
      Contents: '*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/$(MainProjectName).$(Version)-$(Build.BuildNumber).nupkg'
      artifact: 'NuGet package'
      publishLocation: 'pipeline'

  - task: NuGetCommand@2
    displayName: 'Push Nuget'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '06d72d2b-c76a-4d0a-be03-d2ba3a5a3f60/2add6d09-a439-4c6a-83af-cc2405604505'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
