trigger:
- feature/init-azure-pipelines

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

  - task: VSBuild@1
    displayName: "Build UiPath.Session x86"
    inputs:
      solution: "$(SessionSolution)"
      platform: "x86"
      configuration: "$(BuildConfiguration)"
      maximumCpuCount: true
      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Tests*.csproj'
      arguments: '--configuration $(buildConfiguration)'