trigger:
- feature/init-azure-pipelines

pool:
  vmImage: 'windows-2019'

variables:
  BuildConfiguration: 'Release'
  SessionSolution: 'CoreIpc.sln'

steps:

  - task: VSBuild@1
    displayName: "Build"
    inputs:
      solution: '$(SessionSolution)'
      msbuildArgs: '/restore'
      configuration: '$(BuildConfiguration)'
      maximumCpuCount: true
      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Tests*.csproj'
      arguments: '--configuration $(buildConfiguration)'