//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Ipc.TV.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.Ipc.TV.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;$id&quot;:&quot;1&quot;,&quot;$type&quot;:&quot;UiPath.Ipc.Telemetry+ProcessStart, UiPath.Ipc, Version=2.5.1.0, Culture=neutral, PublicKeyToken=null&quot;,&quot;Name&quot;:&quot;UiPath.Executor&quot;,&quot;ProcessId&quot;:19580,&quot;Path&quot;:&quot;D:\\Code\\Studio\\Output\\bin\\Debug\\UiPath.Executor.exe&quot;,&quot;CommandLine&quot;:&quot;D:\\Code\\Studio\\Output\\bin\\Debug\\UiPath.Executor.dll _ _ _ _&quot;,&quot;Framework&quot;:&quot;.NET 8.0.8&quot;,&quot;Is64BitProcess&quot;:true,&quot;Is64BitOS&quot;:true,&quot;CreatedAtUtc&quot;:&quot;2024-09-04T08:45:15.7955569Z&quot;,&quot;Id&quot;:&quot;4a3a28ec9b8b4f16ac319d634ac8bc58&quot;,&quot;MemberName&quot;:null,&quot;FilePath&quot;:null,&quot;Line&quot;:0,&quot;Stac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UiPath_Executor_19580 {
            get {
                return ResourceManager.GetString("UiPath.Executor-19580", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;$id&quot;:&quot;1&quot;,&quot;$type&quot;:&quot;UiPath.Ipc.Telemetry+ProcessStart, UiPath.Ipc, Version=2.5.1.0, Culture=neutral, PublicKeyToken=null&quot;,&quot;Name&quot;:&quot;UiPath.Service.Host&quot;,&quot;ProcessId&quot;:54268,&quot;Path&quot;:&quot;D:\\Code\\Studio\\Output\\bin\\Debug\\UiPath.Service.Host.exe&quot;,&quot;CommandLine&quot;:&quot;D:\\Code\\Studio\\Output\\bin\\Debug\\UiPath.Service.Host.dll -displayname \&quot;UiPath Robot\&quot; -servicename UiRobotSvc&quot;,&quot;Framework&quot;:&quot;.NET 8.0.8&quot;,&quot;Is64BitProcess&quot;:true,&quot;Is64BitOS&quot;:true,&quot;CreatedAtUtc&quot;:&quot;2024-09-04T08:45:11.3609444Z&quot;,&quot;Id&quot;:&quot;5cb41d144fa0448b9a7d4d2f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UiPath_Service_Host_54268 {
            get {
                return ResourceManager.GetString("UiPath.Service.Host-54268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;$id&quot;:&quot;1&quot;,&quot;$type&quot;:&quot;UiPath.Ipc.Telemetry+ProcessStart, UiPath.Ipc, Version=2.5.1.0, Culture=neutral, PublicKeyToken=null&quot;,&quot;Name&quot;:&quot;UiPath.Service.UserHost&quot;,&quot;ProcessId&quot;:37324,&quot;Path&quot;:&quot;D:\\Code\\Studio\\Output\\bin\\Debug\\UiPath.Service.UserHost.exe&quot;,&quot;CommandLine&quot;:&quot;D:\\Code\\Studio\\Output\\bin\\Debug\\UiPath.Service.UserHost.dll&quot;,&quot;Framework&quot;:&quot;.NET 8.0.8&quot;,&quot;Is64BitProcess&quot;:true,&quot;Is64BitOS&quot;:true,&quot;CreatedAtUtc&quot;:&quot;2024-09-04T08:45:13.2722797Z&quot;,&quot;Id&quot;:&quot;356a8e192c384ca49c968e621919bbde&quot;,&quot;MemberName&quot;:null,&quot;FilePath&quot;:nul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UiPath_Service_UserHost_37324 {
            get {
                return ResourceManager.GetString("UiPath.Service.UserHost-37324", resourceCulture);
            }
        }
    }
}
