name: $(Date:yyyyMMdd)$(Rev:-rr)

pool:
  vmImage: 'windows-2019'

variables:
  Label_Initialization: 'Initialization:'
  Label_DotNet: '.NET:'
  Label_NodeJS: 'node.js:'

  DotNet_BuildConfiguration: 'Release'
  DotNet_SessionSolution: 'CoreIpc.sln'
  DotNet_MainProjectName: 'UiPath.CoreIpc'
  DotNet_MainProjectPath: '.\src\UiPath.CoreIpc\UiPath.CoreIpc.csproj'
  DotNet_ArtifactName: 'NuGet package'
  
  NodeJS_ProjectPath: 'src/clients/nodejs'
  NodeJS_ArchivePath: 'src/clients/nodejs.zip'
  NodeJS_ArtifactName: 'NPM package'
  NodeJS_NetCoreAppTargetDir_RelativePath: 'dotnet\UiPath.CoreIpc.NodeInterop\bin\Release\netcoreapp3.1'
  NodeJS_DotNetNodeInteropSolution: 'src/clients/nodejs/dotnet/UiPath.CoreIpc.NodeInterop.sln'

jobs:
  # The following 2 jobs will run in parallel:

  - job:
    displayName: '.NET'
    steps:
      - template: azp-initialization.yaml
      - template: azp-dotnet.yaml

  - job:
    displayName: 'node.js'
    steps:
      - template: azp-initialization.yaml
      - template: azp-nodejs.yaml
